const listings = [
  {
    title: "Red jacket",
    images: ["jacket1"],
    price: 100,
    categoryId: "5f554af255d2b30dd816e279",
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Gray couch in a great condition",
    images: ["couch2"],
    categoryId: "5f554af255d2b30dd816e275",
    price: 1200,
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Room & Board couch (great condition) - delivery included",
    description:
      "I'm selling my furniture at a discount price. Pick up at Venice. DM me asap.",
    images: ["couch1", "couch2", "couch3"],
    price: 1000,
    categoryId: "5f554af255d2b30dd816e275",
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Designer wear shoes",
    images: ["shoes1"],
    categoryId: "5f554af255d2b30dd816e279",
    price: 100,
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Canon 400D (Great Condition)",
    images: ["camera1"],
    price: 300,
    categoryId: "5f554af255d2b30dd816e277",
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Nikon D850 for sale",
    images: ["camera2"],
    price: 350,
    categoryId: "5f554af255d2b30dd816e277",
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Sectional couch - Delivery available",
    description: "No rips no stains no odors",
    images: ["couch3"],
    categoryId: "5f554af255d2b30dd816e275",
    price: 950,
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
  {
    title: "Brown leather shoes",
    images: ["shoes2"],
    categoryId: "5f554af255d2b30dd816e279",
    price: 50,
    userId: "5f554ccf8c0f2c09640ca6ad",
    location: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
  },
];
const categories = [
  {
    name: "Furniture",
    icon: "floor-lamp",
    backgroundColor: "#fc5c65",
    color: "white",
  },
  {
    name: "Cars",
    icon: "car",
    backgroundColor: "#fd9644",
    color: "white",
  },
  {
    name: "Cameras",
    icon: "camera",
    backgroundColor: "#fed330",
    color: "white",
  },
  {
    name: "Games",
    icon: "cards",
    backgroundColor: "#26de81",
    color: "white",
  },
  {
    name: "Clothing",
    icon: "shoe-heel",
    backgroundColor: "#2bcbba",
    color: "white",
  },
  {
    name: "Sports",
    icon: "basketball",
    backgroundColor: "#45aaf2",
    color: "white",
  },
  {
    name: "Movies & Music",
    icon: "headphones",
    backgroundColor: "#4b7bec",
    color: "white",
  },
  {
    name: "Books",
    icon: "book-open-variant",
    backgroundColor: "#a55eea",
    color: "white",
  },
  {
    name: "Other",
    icon: "application",
    backgroundColor: "#778ca3",
    color: "white",
  },
];

const users = [
  {
    email: "test@domain.com",
    name: "Test Man",
    password: "Password1234",
  },
];
const messages = [
  {
    fromUserId: "5f5390378077650abc9c91ba",
    toUserId: "5f5390598077650abc9c91bb",
    listingId: "5f554d41e8291d4584cbbe65",
    content: "Is this still available?",
    dateTime: 1586044521956,
  },
  {
    fromUserId: "5f5390378077650abc9c91ba",
    toUserId: "5f5390598077650abc9c91bb",
    listingId: "5f554d41e8291d4584cbbe65",
    content: "I'm interested in this item. Do you provide free delivery?",
    dateTime: 1586044521956,
  },
  {
    fromUserId: "5f5390378077650abc9c91ba",
    toUserId: "5f5390598077650abc9c91bb",
    listingId: "5f554d41e8291d4584cbbe65",
    content: "Please give me a call and we'll arrange this for you.",
    dateTime: 1586044521956,
  },
];

const subscriptions = [
  {
    name: "Markenting products",
    description:
      "A new product that uploaded last time the much to you - based on AI,\
    Also a new sales notifications",
    platform: "email",
    icon: "cart",
  },
  {
    name: "Transcation confimations",
    description: "A message if transaction like buy or upload product succedd",
    platform: "email",
    icon: "arrow-swap",
  },
];
const coutries = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua And Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia And Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, The Democratic Republic Of The",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Cote D'ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  TP: "East Timor",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GN: "Guinea",
  GW: "Guinea-bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island And Mcdonald Islands",
  VA: "Holy See (vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Korea, Democratic People's Republic Of",
  KR: "Korea, Republic Of",
  KV: "Kosovo",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macau",
  MK: "Macedonia, The Former Yugoslav Republic Of",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States Of",
  MD: "Moldova, Republic Of",
  MC: "Monaco",
  MN: "Mongolia",
  MS: "Montserrat",
  ME: "Montenegro",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  SH: "Saint Helena",
  KN: "Saint Kitts And Nevis",
  LC: "Saint Lucia",
  PM: "Saint Pierre And Miquelon",
  VC: "Saint Vincent And The Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome And Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia And The South Sandwich Islands",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard And Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan, Province Of China",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic Of",
  TH: "Thailand",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks And Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.s.",
  WF: "Wallis And Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};
const states = {
  AL: "Alabama",
  AK: "Alaska",
  AS: "American Samoa",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District Of Columbia",
  FM: "Federated States Of Micronesia",
  FL: "Florida",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MH: "Marshall Islands",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  MP: "Northern Mariana Islands",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PW: "Palau",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VI: "Virgin Islands",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

const mongoose = require("mongoose");
const { Categories } = require("./models/categories");
const { Listings } = require("./models/listings");
const { Message } = require("./models/messages");
const { User } = require("./models/users");
const { Subscription } = require("./models/subscriptions");
const c = require("config");
const { Country } = require("./models/address/countries");
const { State } = require("./models/address/states");
const seed = async () => {
  // await Categories.insertMany(categories);
  // await User.insertMany(users);
  // await Message.insertMany(messages);
  await Subscription.insertMany(subscriptions);
};

// seed();
const main = async () => {
  await mongoose.connect("mongodb://localhost:27017/SellIt", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  console.log("connected to db...");
  // await Listings.insertMany(listings);
  //   await Message.insertMany(messages);
  // await Subscription.insertMany(subscriptions);
  // const usa = await Country.findOne({ codeName: "US" });
  // for (let [codeName, name] of Object.entries(states)) {
  //   await State.create({ name, codeName, country: usa._id });
  // }
  await mongoose.disconnect();
  console.log("done");
};

main();
